name: CI/CD for react Todo

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd react-ci-cd-test
          npm install

      - name: Build Project
        run: |
          cd react-ci-cd-test
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: poduction file
          path: ./react-ci-cd-test/build

  # Deploy Job
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: poduction file
          path: ./react-ci-cd-test/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }} #this is the key of the access token
          publish_dir: ./react-ci-cd-test/build
